#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true


# Restart-safe launches: kill prior instance, wait for it to actually die,
# then relaunch. Picom in particular races on the X compositor selection
# if the old process is still releasing it.
respawn() {
    proc="$1"; shift
    pkill -x "$proc"
    while pgrep -x "$proc" >/dev/null; do sleep 0.05; done
    "$proc" "$@" &
}


# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &
fi


respawn dunst -config ~/.config/dunst/dunstrc
respawn picom --config ~/.config/picom/picom.conf -b


# AutoStart Application
#sxhkd & 
#picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
#dunst &
polybar &
feh --bg-scale ~/Pictures/Wallpapers/002.jpg &
